<!-- vim: set ts=2 sw=2 noet: -->

<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>12</LangVersion>
		<FileAlignment>512</FileAlignment>
		<Deterministic>true</Deterministic>
		<Nullable>enable</Nullable>
		<Version>1.2.2</Version>
		<CopyToMods Condition="'$(CopyToMods)'==''">true</CopyToMods>
	</PropertyGroup>

	<!-- Don't copy references -->
	<ItemDefinitionGroup>
		<Reference>
			<Private>false</Private>
		</Reference>
	</ItemDefinitionGroup>

	<PropertyGroup Condition="'$(ResonitePath)'==''">
		<!-- linux steam -->
		<ResonitePath Condition="Exists('$(HOME)/.steam/steam/steamapps/common/Resonite/')">$(HOME)/.steam/steam/steamapps/common/Resonite/</ResonitePath>
		<!-- windows steam -->
		<ResonitePath Condition="Exists('C:\Program Files (x86)\Steam\steamapps\common\Resonite\')">C:\Program Files (x86)\Steam\steamapps\common\Resonite\</ResonitePath>
		<ResonitePath Condition="Exists('D:\SteamLibrary\steamapps\common\Resonite\')">D:\SteamLibrary\steamapps\common\Resonite\</ResonitePath>
		<ResonitePath Condition="Exists('E:\SteamLibrary\steamapps\common\Resonite\')">E:\SteamLibrary\steamapps\common\Resonite\</ResonitePath>
		<ResonitePath Condition="Exists('F:\SteamLibrary\steamapps\common\Resonite\')">F:\SteamLibrary\steamapps\common\Resonite\</ResonitePath>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>$(ResonitePath)rml_libs\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="ResoniteModLoader">
			<HintPath>$(ResonitePath)Libraries\ResoniteModLoader.dll</HintPath>
		</Reference>
		<Reference Include="Elements.Core">
			<HintPath>$(ResonitePath)Elements.Core.dll</HintPath>
		</Reference>
		<Reference Include="Elements.Assets">
			<HintPath>$(ResonitePath)Elements.Assets.dll</HintPath>
		</Reference>
		<Reference Include="FrooxEngine">
			<HintPath>$(ResonitePath)FrooxEngine.dll</HintPath>
		</Reference>
		<Reference Include="FrooxEngine.Store">
			<HintPath>$(ResonitePath)FrooxEngine.Store.dll</HintPath>
		</Reference>
		<Reference Include="Renderite.Shared">
			<HintPath>$(ResonitePath)Renderite.Shared.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" Version="9.0.9" />
	</ItemGroup>


	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(CopyToMods)'=='true'">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ResonitePath)rml_mods" />
		<Message Text="Copied $(TargetFileName) to $(ResonitePath)rml_mods" Importance="high" />
	</Target>
</Project>
